#!/usr/bin/env bash

function run() {
  app_require_computer_name || return
  app_computer_should_exist || return


  local computer_name=$(app_computer_name)
  run_bash || (
    app_exec lxc start $computer_name && run_bash
  )
}

function run_bash {
  app_exec lxc exec $computer_name bash
}
