#!/usr/bin/env bash

function run {
  local task=$1
  if [ ! -z $task ] && potato_load_task $task >/dev/null; then
    _help $task
  else
    _help_general $@
  fi
}

function _help {
  local task=$1
  [ -z "$task" ] && _help_general || _help_task
}

function _help_task {
  echo 'Implementation:'
  declare -f run
}

function _help_general {
    echo 'Usage: $ computer [@name] task'
    local -a tasks=( "$(potato_tasks_list)" )
    echo "___ Available tasks:"
    printf "   |__ %s\n" ${tasks[@]}
    echo ''
    echo 'To get a task-specific help, run the following:'
    echo '$ computer help $task'
}
