#!/usr/bin/env bash

function run() {
  local computer_name=$(app_computer_name)

  [ -z "$computer_name" ] && app_exec lxc info && return

  app_computer_should_exist || return

  app_exec lxc info $computer_name
  app_exec lxc config show $computer_name
}
