#!/usr/bin/env bash

function run {
  app_require_computer_name || return
  app_computer_should_not_exist || return

  local computer_name=$(app_computer_name)
  local base_name=${1:-"ubuntu:18.04"}
  app_exec lxc launch $base_name $computer_name
}

function _help {
  echo 'Usage:'
  echo 'computer @computer_name init [base_name: ubuntu:18.04]'
  echo 'Implementation:'
  declare -f run
}
