#!/usr/bin/env bash

function run() {
  app_require_computer_name || return
  app_computer_should_exist || return

  local computer_name=$(app_computer_name)
  local login=${1:-ubuntu}
  run_login || (
    app_exec -i lxc start $computer_name && run_login
  )
}

function run_login {
  app_exec lxc exec $computer_name -- sudo --login --user $login
}