#!/usr/bin/env bash

function run() {
  local computer_name=$(app_computer_name)
  # @TODO potential for ambiguty
  if [ "$computer_name" = "default" ]; then
    potato_run_task help
    return
  fi
  local lxc_command=$1
  # @TODO this does not work for cases like 'config show' where the command is more than 2 words
  shift
  ! app_validate_computer_exists $computer_name && echo 'Computer '$computer_name' does not exist.' && return
  app_exec lxc $lxc_command $computer_name $@
}
